# Generated by Django 4.2.29 on 2026-04-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('image_url', models.URLField(blank=True, default='', max_length=800)),
                ('alt', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_enabled', models.BooleanField(default=True)),
                ('alert_message', models.CharField(default='In the event of adverse weather, please contact your teacher individually to arrange a virtual lesson.', max_length=255)),
                ('phone_display', models.CharField(default='(704) 676-1002', max_length=60)),
                ('phone_tel', models.CharField(default='+17046761002', max_length=30)),
                ('email', models.EmailField(default='info@southernparkmusicschool.com', max_length=254)),
                ('address', models.TextField(default='4805 Park Rd STE 230\nCharlotte, NC 28209')),
                ('hours_weekday', models.CharField(default='9AM–9PM', max_length=30)),
                ('hours_saturday', models.CharField(default='9AM–2PM', max_length=30)),
                ('calendar_embed_url', models.URLField(blank=True, default='', max_length=1000)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
