# Generated by Django 4.2.29 on 2026-04-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('instrument_tag', models.CharField(help_text="Space-separated tags for search filtering, e.g. 'piano voice'", max_length=60)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='faculty/')),
                ('bio', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Faculty Member',
                'verbose_name_plural': 'Faculty Members',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
