# Generated by Django 4.2.21 on 2026-04-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryvideo',
            name='youtube_url',
            field=models.TextField(help_text='Paste the YouTube embed code (<iframe ...>) from Share → Embed, or a plain YouTube URL (youtu.be/... or youtube.com/watch?v=...).'),
        ),
    ]
