# Generated by Django 4.2.21 on 2026-04-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_youtube_url_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryvideo',
            name='youtube_url',
            field=models.CharField(help_text='Paste the YouTube video link, e.g. https://youtu.be/abc123 or https://www.youtube.com/watch?v=abc123', max_length=500),
        ),
    ]
